spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.193.68:3306/shihui?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
        0
      max-file-size:
        500MB
      max-request-size:
        500MB
  freemarker:
    cache: true
    charset: UTF-8
    suffix: .html
    content-type: text/html
server:
  port: 8989
  servlet:
    context-path: /SH
logging:
  level:
    com.yy.spring.dao: debug
mybatis:
  type-aliases-package: com.shzp.entity
  mapper-locations:
  - classpath:mapper/*.xml
